### ISSUE TITLE
Error: executed() missing 1 positional argument: 'maintainBridgeValue'

### ISSUE THREAD

**Issue by Arturoo** [kartchnb/AutoTowersGenerator#17]
Hi, I am trying to print a fan tower but I keep getting this error when trying to save the gcode and it wont save, if I try to save it again without regenerating the tower it will save but will not do the intended function. All the other towers do work. Cura 5.1.1

**Comment by kartchnb** [comment]
Thank you for reporting this. This was yet another stupid error that I completely missed somehow. It should be fixed in version 2.3.0 of the plugin, which will be showing up in the Cura Marketplace soon.  If you want to upgrade now, you can easily do it manually:

- Download the .curapackage file for Cura 5.1.0 from here: https://github.com/kartchnb/AutoTowersGenerator/releases/download/v2.3.0/AutoTowersGenerator-v8.1.0-Cura5.1.0.curapackage
- Start Cura
- Drag and drop the .curapackage file from your file manager to the Cura window and it should install.
