### ISSUE TITLE
Linked Cura Settings (SymLink), Plugin not working

### ISSUE THREAD

**Issue by bbraeu** [kartchnb/AutoTowersGenerator#21]
Hi,

unfortunately the plugin is not working when the directory for the cura settings is linked via a symlink.
I created the link to be able to sync the settings via OneDrive:
mklink /d C:\Users\<Username>\AppData\Roaming\cura C:\Users\<Username>\OneDrive\3DDruck\CuraSettings

With this setup i get the following error when i try to create a custom tower:

![image](https://user-images.githubusercontent.com/48953225/197178952-3b4a3334-7745-450d-9dbe-4830317e1d58.png)

**Comment by kartchnb** [comment]
That is unfortunate. That appears to be an issue with OpenSCAD itself.

There may be something I can do to work around the issue.  I'll give it some thought.  

Thank you for letting me know!

**Comment by kartchnb** [comment]
Okay, I think I've figured out a fix for this.

Although I can't fix the underlying problem with OpenSCAD, I've tried to implement a work-around. If an OpenSCAD source file is in a symlink directory, my plugin will now copy it to the system's temporary directory and have OpenSCAD process it from there. This *should* fix the issue, although I can't test it on my system to be sure.

If you get a moment, please try version 2.4.2 of my plugin, which you can find here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.4.2

If you just download the .curapackage file that matches your version of Cura, you can install it by dragging and dropping it onto a running Cura window.

If you don't mind letting me know if it works, I would appreciate it.

Thank you again!

**Comment by bbraeu** [comment]
Hi, unfortunately i still get the same error :-(
Maybe it is because my whole Cura settings directory is a link and nur just the directory with the scad files?

**Comment by kartchnb** [comment]
Maybe, but it seems like that shouldn't be an issue.  I'll have to spend some time trying to duplicate the problem and write a proper fix for it.

**Comment by kartchnb** [comment]
I finally found time to duplicate the issue and I think I have a fix.  

The problem occurs if any of the folders in the plugin path are symlinks.  My plugin now checks for this and copies OpenScad scripts to a temporary location, which seems to work now.  I would appreciate a second set of eyes on this, though.

The fix is in release 2.6.1, which you can find here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.6.1

Just download the .curapackage that corresponds to your version of Cura and drag and drop it onto a running Cura Window to install it.

**Comment by kartchnb** [comment]
I believe this is fixed.  Closing it for now.
