### ISSUE TITLE
Flow sections labeled incorrectly

### ISSUE THREAD

**Issue by wrathernaut** [kartchnb/AutoTowersGenerator#46]
The bottom of the default tower is labeled "85", but the first section is set to 115.
`;LAYER:4
M221 S115 ; AutoTowersGenerator setting flow rate to 115 for first section
`
`;LAYER:244
M221 S85 ; AutoTowersGenerator setting flow rate to 85 for next section
`
But generates a tower that looks like this.

![image](https://user-images.githubusercontent.com/97267123/208221421-9241cd94-9fd4-47e8-ac20-ef8a63102217.png)

**Comment by kartchnb** [comment]
You are absolutely correct.  This is a particularly embarrassing error that I made, but I always appreciate when people are willing to submit bug reports.  Thank you!

This should be fixed in version 2.6.0, which you can find here: https://github.com/kartchnb/AutoTowersGenerator/releases/tag/v2.6.0

It will, hopefully, be up on the Marketplace at some point, but it takes a while.
