### ISSUE TITLE
Speed Tower

### ISSUE THREAD

**Issue by mattiasthalen** [kartchnb/AutoTowersGenerator#81]
Hi,

Shouldn’t the speed tower automatically set walls to 1, infill 0%, and minimum layer time to something like 3s?

**Comment by kartchnb** [comment]
I'm hesitant to enforce too many settings because I want people to be able to generate these towers using the settings they would normally print at.  Forcing walls to 1 might result in differences between how the speed tower prints and how other prints do.  Maybe not, but, for now, I don't think I'll enforce this.  You can easily change these settings yourself before slicing.

I'm always open to being wrong, though.

I appreciate the suggestion.  Thank you!
